package arduinojava;

/**
 * @author Name: Shahin Mokhtar Moshfeghi HvA Id: 500669336 Class: IS202
 */
import java.awt.Color;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.net.MalformedURLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import java.io.FileWriter; //to write to .csv file
import javax.swing.ImageIcon;
import javax.swing.filechooser.FileNameExtensionFilter;

public class GUI extends javax.swing.JFrame {

    /**
     * Passed from ArduinoJava, OpenFile and ImageByte
     */
    ArduinoJava aj = null;
    OpenFile of = null;
    ImageByte ib = null;

    //current user on preview
    private int currentUser = 0;

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
        createObjects();
        aj.searchForPorts();
    }

    private void createObjects() {
        aj = new ArduinoJava(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        userAddDialog = new javax.swing.JDialog();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        logLbl = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtLog = new javax.swing.JTextArea();
        btnDisconnect = new javax.swing.JButton();
        btnConnect = new javax.swing.JButton();
        cboxPorts = new javax.swing.JComboBox();
        deviceConnectedLbl = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        onPortLbl = new javax.swing.JLabel();
        deviceConnected = new javax.swing.JLabel();
        onPort = new javax.swing.JLabel();
        clearLog = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        clearArduino = new javax.swing.JButton();
        cLogo = new javax.swing.JLabel();
        connectionLbl = new javax.swing.JLabel();
        jPanel = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        display = new javax.swing.JLabel();
        dLogo = new javax.swing.JLabel();
        uOlbl = new javax.swing.JLabel();
        fnOlbl = new javax.swing.JLabel();
        lnOlbl = new javax.swing.JLabel();
        fosOlbl = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        nextUserBtn = new javax.swing.JButton();
        browseCsv = new javax.swing.JButton();
        selectLogo = new javax.swing.JButton();
        writeTo = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        universityLbl = new javax.swing.JLabel();
        universityField = new javax.swing.JTextField();
        firstnameLbl = new javax.swing.JLabel();
        firstNameField = new javax.swing.JTextField();
        lastnameLbl = new javax.swing.JLabel();
        lastNameField = new javax.swing.JTextField();
        fosLbl = new javax.swing.JLabel();
        addButton = new javax.swing.JButton();
        fieldOfStudyField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        userAddDialog.setBounds(new java.awt.Rectangle(200, 22, 300, 340));
        userAddDialog.setEnabled(false);
        userAddDialog.setFocusableWindowState(false);

        javax.swing.GroupLayout userAddDialogLayout = new javax.swing.GroupLayout(userAddDialog.getContentPane());
        userAddDialog.getContentPane().setLayout(userAddDialogLayout);
        userAddDialogLayout.setHorizontalGroup(
            userAddDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        userAddDialogLayout.setVerticalGroup(
            userAddDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 297, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Name tag");
        setMaximumSize(new java.awt.Dimension(1220, 571));
        setResizable(false);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/diamond.jpg"))); // NOI18N

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setOpaque(false);

        logLbl.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        logLbl.setForeground(new java.awt.Color(255, 255, 255));
        logLbl.setText("Log");

        txtLog.setEditable(false);
        txtLog.setColumns(20);
        txtLog.setLineWrap(true);
        txtLog.setRows(5);
        txtLog.setFocusable(false);
        jScrollPane2.setViewportView(txtLog);

        btnDisconnect.setText("Disconnect");
        btnDisconnect.setEnabled(false);
        btnDisconnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisconnectActionPerformed(evt);
            }
        });

        btnConnect.setText("Connect");
        btnConnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConnectActionPerformed(evt);
            }
        });

        cboxPorts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxPortsActionPerformed(evt);
            }
        });

        deviceConnectedLbl.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        deviceConnectedLbl.setForeground(new java.awt.Color(255, 255, 255));
        deviceConnectedLbl.setText("Device connected:");

        jLabel1.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Select COM port");

        onPortLbl.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        onPortLbl.setForeground(new java.awt.Color(255, 255, 255));
        onPortLbl.setText("On port:");

        deviceConnected.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        deviceConnected.setForeground(new java.awt.Color(255, 255, 255));

        onPort.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        onPort.setForeground(new java.awt.Color(255, 255, 255));

        clearLog.setText("Clear log");
        clearLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearLogActionPerformed(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/logo_1.png"))); // NOI18N

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/line.gif"))); // NOI18N

        clearArduino.setText("Clear Arduino");
        clearArduino.setEnabled(false);
        clearArduino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearArduinoActionPerformed(evt);
            }
        });

        connectionLbl.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        connectionLbl.setForeground(new java.awt.Color(255, 255, 255));
        connectionLbl.setText("Connection");

        jPanel.setBackground(new java.awt.Color(255, 255, 255));
        jPanel.setEnabled(false);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setOpaque(false);

        jPanel2.setOpaque(false);

        display.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/scherm.png"))); // NOI18N

        dLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/logo_1.png"))); // NOI18N

        uOlbl.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        uOlbl.setForeground(new java.awt.Color(255, 255, 255));
        uOlbl.setText("university");

        fnOlbl.setFont(new java.awt.Font("Calibri Light", 0, 36)); // NOI18N
        fnOlbl.setForeground(new java.awt.Color(255, 255, 255));
        fnOlbl.setText("first name");

        lnOlbl.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        lnOlbl.setForeground(new java.awt.Color(255, 255, 255));
        lnOlbl.setText("last name");

        fosOlbl.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        fosOlbl.setForeground(new java.awt.Color(255, 255, 255));
        fosOlbl.setText("field of study");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(uOlbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(217, 217, 217))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fnOlbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lnOlbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(434, 434, 434))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dLogo)
                            .addComponent(fosOlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(display, javax.swing.GroupLayout.PREFERRED_SIZE, 603, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(dLogo)
                .addGap(27, 27, 27)
                .addComponent(uOlbl)
                .addGap(18, 18, 18)
                .addComponent(fnOlbl)
                .addGap(18, 18, 18)
                .addComponent(lnOlbl)
                .addGap(18, 18, 18)
                .addComponent(fosOlbl)
                .addContainerGap(141, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(display, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        nextUserBtn.setText("Next user");
        nextUserBtn.setEnabled(false);
        nextUserBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextUserBtnActionPerformed(evt);
            }
        });

        browseCsv.setText("Select .csv");
        browseCsv.setEnabled(false);
        browseCsv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseCsvActionPerformed(evt);
            }
        });

        selectLogo.setText("Select logo");
        selectLogo.setEnabled(false);
        selectLogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectLogoActionPerformed(evt);
            }
        });

        writeTo.setText("Write");
        writeTo.setEnabled(false);
        writeTo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                writeToActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(writeTo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 200, Short.MAX_VALUE)
                .addComponent(nextUserBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(browseCsv)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(selectLogo)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selectLogo)
                    .addComponent(browseCsv)
                    .addComponent(nextUserBtn)
                    .addComponent(writeTo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jPanel.addTab("File content", jPanel4);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        universityLbl.setText("University:");

        universityField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        universityField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                universityFieldActionPerformed(evt);
            }
        });

        firstnameLbl.setText("First Name:");

        firstNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNameFieldActionPerformed(evt);
            }
        });

        lastnameLbl.setText("Lastname:");

        lastNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastNameFieldActionPerformed(evt);
            }
        });

        fosLbl.setText("Field of Study");

        addButton.setText("Add");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        fieldOfStudyField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldOfStudyFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(universityLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(universityField, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(firstnameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(firstNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lastnameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lastNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fosLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fieldOfStudyField, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(addButton)))
                .addContainerGap(345, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(universityLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(universityField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(firstnameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(firstNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lastnameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lastNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fosLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldOfStudyField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(addButton)
                .addContainerGap(266, Short.MAX_VALUE))
        );

        jPanel.addTab("Add user", jPanel5);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 1072, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(cLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 608, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnConnect, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(cboxPorts, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(btnDisconnect, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(connectionLbl)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(deviceConnectedLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deviceConnected))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(onPortLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(onPort)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logLbl)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(clearArduino)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(clearLog))
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton1))
                .addGap(13, 13, 13))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 1, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(connectionLbl)
                            .addComponent(logLbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(cboxPorts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnConnect)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnDisconnect)
                                .addGap(88, 88, 88)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(deviceConnectedLbl)
                                    .addComponent(deviceConnected))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(onPortLbl)
                                    .addComponent(onPort)))
                            .addComponent(jScrollPane2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(clearArduino)
                            .addComponent(clearLog))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(128, 128, 128))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1233, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 622, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConnectActionPerformed
        aj.connect();
        if (aj.getConnected() == true) {
            if (aj.initIOStream() == true) {
                aj.initListener();

                /**
                 * Enable buttons: Browse, Disconnect, Clear Arduino, Upload
                 * Automatically, Upload manually, Select logo
                 */
                browseCsv.setEnabled(true);
                btnDisconnect.setEnabled(true);
                clearArduino.setEnabled(true);
                writeTo.setEnabled(true);
                selectLogo.setEnabled(true);

                /**
                 * Disable: Connect button, COM port combo box
                 */
                btnConnect.setEnabled(false);
                cboxPorts.setEnabled(false);

                /**
                 * If device is connected, set text to true
                 */
                Boolean devCon = aj.getConnected();
                deviceConnected.setText(devCon.toString());

                /**
                 * If device is connected, set text: which COM port
                 */
                onPort.setText(cboxPorts.getSelectedItem().toString());
            }
        }
    }//GEN-LAST:event_btnConnectActionPerformed

    private void btnDisconnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisconnectActionPerformed
        aj.disconnect();

        /**
         * Disable buttons: Browse, Disconnect, Clear Arduino, Upload
         * Automatically, Upload manually, Select logo,
         */
        browseCsv.setEnabled(false);
        btnDisconnect.setEnabled(false);
        clearArduino.setEnabled(false);
        writeTo.setEnabled(false);
        selectLogo.setEnabled(false);

        /**
         * Enable: Connect button, COM port combo box
         */
        btnConnect.setEnabled(true);
        cboxPorts.setEnabled(true);

        /**
         * If device is disconnect, set text to false
         */
        Boolean devCon = aj.getConnected();
        deviceConnected.setText(devCon.toString());

        /**
         * If device is disconnected, set text: empty String
         */
        onPort.setText("");
    }//GEN-LAST:event_btnDisconnectActionPerformed

    private void cboxPortsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxPortsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboxPortsActionPerformed

    private void clearLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearLogActionPerformed
        /**
         * Clear log
         */
        txtLog.setText(null);
    }//GEN-LAST:event_clearLogActionPerformed

    private void clearArduinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearArduinoActionPerformed
        /**
         * String to char converter
         */
//        String strR = "Cleared";
//        int strLengthR = strR.length();
//        for (int i = 0; i < strLengthR; i++) {
//            char charAR = strR.charAt(i);
//            aj.writeData(charAR);
//        }
    }//GEN-LAST:event_clearArduinoActionPerformed

    private void browseCsvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseCsvActionPerformed
        /**
         * File filters, only show images and directories in file chooser
         */
        of = new OpenFile();
        FileNameExtensionFilter fnef = new FileNameExtensionFilter("CSV", "csv");
        of.fileChooser.setAcceptAllFileFilterUsed(false);
        of.fileChooser.setFileFilter(fnef);

        /**
         * Browse for file (OpenFile.java, openTxtFile())
         */
        of = new OpenFile();
        try {
            of.openCsv();
        } catch (Exception e) {
            e.printStackTrace();
        }

        /**
         * Set content of file in the text area
         */
        //displayPreview.setText(of.data.toString() + "Lastname: " + of.lastName + "\n");
//        displayPreview.setText(of.userList.get(currentUser).getUserString());
        nextUserBtn.setEnabled(true);
//        addUserBtn.setEnabled(true);
        System.out.println(of.data);

        /**
         * Enable JPanel for adding a new user
         */
        jPanel.setEnabled(true);
    }//GEN-LAST:event_browseCsvActionPerformed

    private void writeToActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_writeToActionPerformed
        /**
         * String to char converter and write to Arduino
         */
//        String str = "University";
//        int strLength = str.length();
//        for (int i = 0; i < strLength; i++) {
//            char charA = str.charAt(i);
//            aj.writeData(charA);
//        }

        /**
         * String to char converter and write to Arduino
         */
//        String cName = cpnyName.getText();
//        for (int i = 0; i < 30; i++) {
//            char coName = cName.charAt(i);
//            aj.writeData(coName);
//        }
    }//GEN-LAST:event_writeToActionPerformed

    private void selectLogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectLogoActionPerformed
        /**
         * File filters, only show images and directories in file chooser
         */
        of = new OpenFile();
        FileNameExtensionFilter fnef = new FileNameExtensionFilter("Images", "pbm", "jpg", "jpeg", "png", "gif");
        of.fileChooser.setAcceptAllFileFilterUsed(false);
        of.fileChooser.setFileFilter(fnef);

        /**
         * Browse for file (OpenFile.java, openImage())
         */
        ib = new ImageByte();
        try {
            of.openImage();
        } catch (Exception e) {
            e.printStackTrace();
        }

        /**
         * create ImageIcon, then set the icon Image to cLogo
         */
        try {
            ImageIcon icon = new ImageIcon(of.fileChooser.getSelectedFile().toURL());
            cLogo.setIcon(icon);
            /* Test image to string and string to image finish */
        } catch (MalformedURLException ex) {
            Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
        }

        /**
         * Encode image to string imgstr, decode String to image newImg and
         * write to new destination
         */
//        try {
//            /* Test image to string and string to image start */
//            BufferedImage img = ImageIO.read(new File(of.fileChooser.getSelectedFile().toString()));
//            BufferedImage newImg;
//            String imgstr;
//            imgstr = ib.encodeToString(img, "png");
//            System.out.println(imgstr);
//            newImg = ib.decodeToImage(imgstr);
//            ImageIO.write(newImg, "png", new File("D:\\NetBeansProjects\\ArduinoJava\\src\\resource\\logo.png"));
//        } catch (IOException e) {
//            e.printStackTrace();
//        }
        /**
         * Encode BMP to int array bmpStr
         */
        ib = new ImageByte();
        try {
            ib.seeBMPImage(null);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_selectLogoActionPerformed

    private void nextUserBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextUserBtnActionPerformed
        //go to the next user if possible, otherwise go to begin of list
        if (currentUser < of.userList.size() - 1) {
            currentUser++;
        } else {
            currentUser = 0;
        }
        
        //print the next user to the screen
        uOlbl.setText(of.userList.get(currentUser).getUniversity());
        fnOlbl.setText(of.userList.get(currentUser).getFirstName());
        lnOlbl.setText(of.userList.get(currentUser).getLastName());
        fosOlbl.setText(of.userList.get(currentUser).getFieldOfStudy());
    }//GEN-LAST:event_nextUserBtnActionPerformed

    private void universityFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_universityFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_universityFieldActionPerformed

    private void firstNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstNameFieldActionPerformed

    private void lastNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastNameFieldActionPerformed

    private void fieldOfStudyFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldOfStudyFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldOfStudyFieldActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        /**
         * Get text field content
         */
        String uT = universityField.getText();
        String fN = firstNameField.getText();
        String lN = lastNameField.getText();
        String fS = fieldOfStudyField.getText();

        /**
         * Clear text log
         */
        txtLog.setText(null);

        /**
         * Check if text field is empty, set label color of empty text field to
         * red, else set it to black. If all text fields are filled in, add new
         * user.
         */
        if (uT.length() == 0) {
            // Set label color to red, and print message in the log 
            universityLbl.setForeground(Color.red);
            txtLog.append("Please fill in the University. \n");
        } else {
            // Set label color to black
            universityLbl.setForeground(Color.black);
        }
        if (fN.length() == 0) {
            firstnameLbl.setForeground(Color.red);
            txtLog.append("Please fill in the First name. \n");
        } else {
            firstnameLbl.setForeground(Color.black);
        }
        if (lN.length() == 0) {
            lastnameLbl.setForeground(Color.red);
            txtLog.append("Please fill in the Last name. \n");
        } else {
            lastnameLbl.setForeground(Color.black);
        }
        if (fS.length() == 0) {
            fosLbl.setForeground(Color.red);
            txtLog.append("Please fill in the Field of study. \n");
        } else {
            fosLbl.setForeground(Color.black);
        }
        if (uT.length() != 0 && fN.length() != 0 && lN.length() != 0 && fS.length() != 0) {
            //create a user and write to csv file
            User tempUser = new User();
            tempUser.setUniversity(uT);
            tempUser.setFirstName(fN);
            tempUser.setLastName(lN);
            tempUser.setFieldOfStudy(fS);
            tempUser.writeUserToCsvFile(of.file);

            // Add the user to the userList
            of.userList.add(tempUser);

            // Print add message in the log
            txtLog.setText("New user added");

            // Empty text fields
            universityField.setText(null);
            firstNameField.setText(null);
            lastNameField.setText(null);
            fieldOfStudyField.setText(null);
        }
    }//GEN-LAST:event_addButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        browseCsv.setEnabled(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton browseCsv;
    public javax.swing.JButton btnConnect;
    public javax.swing.JButton btnDisconnect;
    private javax.swing.JLabel cLogo;
    public javax.swing.JComboBox cboxPorts;
    private javax.swing.JButton clearArduino;
    private javax.swing.JButton clearLog;
    private javax.swing.JLabel connectionLbl;
    private javax.swing.JLabel dLogo;
    private javax.swing.JLabel deviceConnected;
    private javax.swing.JLabel deviceConnectedLbl;
    private javax.swing.JLabel display;
    private javax.swing.JTextField fieldOfStudyField;
    private javax.swing.JTextField firstNameField;
    private javax.swing.JLabel firstnameLbl;
    private javax.swing.JLabel fnOlbl;
    private javax.swing.JLabel fosLbl;
    private javax.swing.JLabel fosOlbl;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTabbedPane jPanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField lastNameField;
    private javax.swing.JLabel lastnameLbl;
    private javax.swing.JLabel lnOlbl;
    private javax.swing.JLabel logLbl;
    private javax.swing.JButton nextUserBtn;
    private javax.swing.JLabel onPort;
    private javax.swing.JLabel onPortLbl;
    private javax.swing.JButton selectLogo;
    public javax.swing.JTextArea txtLog;
    private javax.swing.JLabel uOlbl;
    private javax.swing.JTextField universityField;
    private javax.swing.JLabel universityLbl;
    private javax.swing.JDialog userAddDialog;
    private javax.swing.JButton writeTo;
    // End of variables declaration//GEN-END:variables
}
